# Generated by Django 4.2.5 on 2024-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='textarea',
            new_name='img',
        ),
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='main',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
