# Generated by Django 4.2.5 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_rename_textarea_main_img_main_image_main_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='image',
        ),
        migrations.AlterField(
            model_name='main',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
