# Generated by Django 4.2.5 on 2024-02-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_remove_main_image_alter_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='gifting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
