# Generated by Django 4.2.5 on 2024-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('Number', models.CharField(blank=True, max_length=15, null=True)),
                ('category', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
            ],
        ),
    ]
