# Generated by Django 4.2.5 on 2024-02-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_contact3'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link1', models.CharField(max_length=30)),
                ('link2', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='contact3',
            old_name='Number',
            new_name='number',
        ),
    ]
