# Generated by Django 4.2.5 on 2024-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifting',
            name='sub_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
