# Generated by Django 4.2.5 on 2024-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_gifting_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='sub_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
