# Generated by Django 4.2.5 on 2024-02-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
