# Generated by Django 4.2.5 on 2024-03-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='discription1',
            new_name='description1',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='discription2',
            new_name='description2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='discription3',
            new_name='description3',
        ),
        migrations.RenameField(
            model_name='gifting',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='discription',
            new_name='description',
        ),
    ]
