# Generated by Django 4.2.5 on 2024-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_rename_discription1_blog_description1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gifting',
        ),
        migrations.AddField(
            model_name='main',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
