# Generated by Django 4.2.5 on 2024-04-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_delete_gifting_main_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='link2',
        ),
    ]
