# Generated by Django 4.2.5 on 2024-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_alter_blog_date_alter_deal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
