# Generated by Django 4.2.5 on 2024-04-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_adminpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
