# Generated by Django 4.2.5 on 2024-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.AddField(
            model_name='contact',
            name='Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
