# Generated by Django 4.2.5 on 2024-02-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='main',
        ),
    ]
