# Generated by Django 4.2.5 on 2024-02-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_admin_main'),
    ]

    operations = [
        migrations.DeleteModel(
            name='main',
        ),
    ]
