# Generated by Django 4.2.5 on 2024-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productemail',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
