# Generated by Django 4.2.5 on 2024-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='address',
            field=models.CharField(max_length=50, null=2),
            preserve_default=2,
        ),
    ]
