# Generated by Django 4.2.5 on 2024-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
