# Generated by Django 4.2.5 on 2024-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
