# Generated by Django 4.2.5 on 2024-04-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_checkout_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('productid', models.CharField(max_length=20)),
                ('productname', models.CharField(max_length=20)),
                ('productimage', models.CharField(max_length=20)),
                ('productprice', models.CharField(max_length=20)),
                ('productemail', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
